### ISSUE TITLE
Didn't work with typescript 2.1

### ISSUE THREAD

**Issue by yeluoqiuzhi** [shellscape/koa-webpack#16]
typescropt 2.1 has supported async function,
but this module can't work with typescript,
it yield some error:
```
module.js:474
    throw err;
    ^

Error: Cannot find module 'babel-runtime/core-js/object/assign'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/donghuashen/work/gitversion/OA/node_modules/koa-webpack/dist/index.js:7:15)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
```

**Comment by shellscape** [comment]
sorry, I don't work with Typescript and have no desire to 😄 I would totally welcome a pull request fixing whatever issue you're running into though!

**Comment by joelday** [comment]
@yeluoqiuzhi Just add babel-runtime to your devDependencies.

**Comment by yeluoqiuzhi** [comment]
thanks

**Comment by shellscape** [comment]
thanks for the followup @joelday
